### ISSUE TITLE
Spanish Translation Menu Screens Review

### ISSUE THREAD

**Issue by alsama** [andan67/wormnav#10]
Thanks for use the FONT_SMALL font in Data screens Labels, is really better than FONT_XTINY font to read it.

Now I'd like to show you a difference that exists in menus and some screens bettween garmin Simulator and a Real Device like vivoactive 3. But I think that It will happend in all CIQ 3.X devices.

![wormnav_texts_07](https://user-images.githubusercontent.com/28567374/116146487-d9aee380-a6de-11eb-8442-8fc03ed4c0f3.jpg)
![wormnav_texts_08](https://user-images.githubusercontent.com/28567374/116146526-e16e8800-a6de-11eb-8aa8-498133fb0952.jpg)

In the case of picker control. You can see that in simulator you can see more text, that what is showed in a real device.
So the String "Num. Campos" and string "Campos de datos" are not full showed. So that text strings must be reduced. 

I think that in general texts in picker labels must be lower that 10 characters.

**Comment by andan67** [comment]
Thanks for the review. 

I've created a new branch 'new_menu' where the GenericPicker has been replaced by a new menu based on the work from https://github.com/davebaldwin/Dmenu.

I hope that with the new menu the limitations and display issues induced by the Picker based implementation are gone.

I will likely merge this branch into master in the next days.

**Comment by alsama** [comment]
I think that is Great change to use the "Dmenu" because is a menu similar to Menu screen that is used in CIQ 3.x devices, and you can use it in fr235. Even in simulator seems that this new version (for fr235) is using less memory than old version.

I just saw that in last commit you have eliminate "/n" from texts labels that in some cases draw text out of the menu space.

I think that this new menu could be even better if you inprove it making it to show in each menu option the text of the menu option and other text under with the option that is selected inside. Just like "WatchUi.Menu2" that is provided with CIQ 3.x devices where you can add any "MenuItem" with a label and a sublabel text. So you can scroll menu seeing what option is selected in each option.

Also I suggest that for screen menu maybe will be more simple have the following menu structure:
Data screens:
-Menu1: Defaults.
-Menu2: Screen 1
-Menu3: Screen 2
-Menu4: Screen 3
-Menu5: Screen 4

-Screen X:
-Menu1: #Fields.
-Menu2: Field 1
-Menu3: Field 2
-Menu4: Field 3
-Menu5: Field 4

And could enter in each field to select the value you want to configure for that field.

So when by enter in any screen you can configure the number of fields or go directly to configure any field without having to configure all the fields each time. 
So you could go to configure just one field.
And in the menu you can see what values you have in each field using a Menu with label and sublabel texts that I comment before.

**Comment by andan67** [comment]
I've created a new branch new_menu_2 where I've tried to implement your above suggestions. This is still WIP and not yet optimized. But it would be great if you could do a first check if this version is functioning well on your device.
I think I will have a final version for release within the next week.

**Comment by alsama** [comment]
I have try "new_menu_2" brach and copied it to my vivoactive 3. Now all menus works great. All strings are big and easy to read and label and sublabel menus makes that to change or consult any configuration very intuituve and functional.
Congratulations.
I attach some screens:
![wormnav_texts_09](https://user-images.githubusercontent.com/28567374/117721989-d2103400-b1e0-11eb-8bee-a4ee137c67d3.jpg)


Only say that string "dfm_labels" is not defined in spanish language so that texts are only in english:
`<string id="dfm_labels"># Fields|Field 1|Field 2|Field 3|Field 4</string> `

**Comment by andan67** [comment]
New menu released in version 1.5
