### ISSUE TITLE
Spanish translation issue

### ISSUE THREAD

**Issue by alsama** [andan67/wormnav#12]
Hello Andan:

I have found a little issue in spanish translation of "df_labels" string

`    <string id="df_labels">Tiempo|Distancia|Ritmo|Velocidad|Ritmo med.|Vel. media|FC media|%FC máx.|FC media|Tiempo v.|Dist. vuelta|Rit. vuel.|Vel. vuelta|Rmo ú. vue|Vel. ú. vue|Vueltas|Altitud|Hora del día|Batería</string>
`

the first "**FC media**" label must be "**Frec. card.**"

so that string must be:
`    <string id="df_labels">Tiempo|Distancia|Ritmo|Velocidad|Ritmo med.|Vel. media|Frec. card.|%FC máx.|FC media|Tiempo v.|Dist. vuelta|Rit. vuel.|Vel. vuelta|Rmo ú. vue|Vel. ú. vue|Vueltas|Altitud|Hora del día|Batería</string>`

Also in "dm_labels" string some labels could be shorter:
`    <string id="dm_labels">Tiempo|Distancia|Ritmo|Velocidad|Ritmo medio|Velocidad media|Frecuencia cardiaca|Frec. card. % máx.|Frec. card. media|Tiempo de vuelta|Distance vuelta|Ritmo vuelta|Velocidad vuelta|Ritmo en ult. vuelta|Veloc. de ult. vuelta|Vueltas|Altitud|Hora del día|Batería</string>`

"Ritmo **en** ult. vuelta" could be: "**Ritmo ult. vuelta**"
"Veloc. **de** ult. vuelta" could be: "**Veloc. ult. vuelta**"

And "**Distance** vuelta" must be "**Distancia** vuelta"

Thank you.

**Comment by andan67** [comment]
Fixed in WormNav 1.6 version
