### ISSUE TITLE
Show Play/Pause indicator

### ISSUE THREAD

**Issue by memen45** [andan67/wormnav#13]
Often when cycling I forget to start the activity again after a longer break. The only way to notice this is to look at the watch for two seconds to verify the clock is ticking. However on the bike I only glance at the watch to check the route, so I only notice the mistake after a while.

Would it be possible to show a Play/Pause/Stop icon or maybe color the text based on the activity recording state such that one can see instantly whether the activity is being recorded?

**Comment by andan67** [comment]
Fixes in WormNav1.6.x version (use of red font color for activity data on course screen when activity is paused)
