### ISSUE TITLE
Allow 'closing' the app while recording

### ISSUE THREAD

**Issue by memen45** [andan67/wormnav#14]
With the default Garmin activity apps it is possible to swipe right to show the clock again and use the other widgets on the device (Vivoactive 4s). However, with wormnav this results in the dialog 'Exit App'. 

Would it be possible to still use the other features of the watch while recording with wormnav (or while recording is paused)? Especially when having a short break it would be useful to be able to check time or music etc.

**Comment by andan67** [comment]
I don't think this is possible programmatically. Have you tried the 'onhold' event (press screen for > 1s)? From the Garmin forum I undertstand this would bring up the clock for (possibly older) VA devices.
