### ISSUE TITLE
vivoactive 4 compatibility?

### ISSUE THREAD

**Issue by markwmuller** [andan67/wormnav#2]
Hi, this app looks great. I see it is compatible with the VA3, but not VA4. Is there a fundamental reason, or (and I'm being an optimist :) ) is this a simple fix to make also compatible with the newer (and presumably more capable) device?

ETA -- personally, I'd like Vivoactive 4S

**Comment by markwmuller** [comment]
I hacked together a WIP PR  #4  for this. It's not elegant, and I don't really know what I'm doing (just downloaded all the tools for the first time!), but it seems to work on the VA4s. 
I don't have the skills /time to make it nice, it definitely needs some settings modifications to tell it that it is, in fact, compatible with VA4.

**Comment by andan67** [comment]
Hi. There is no fundamental reason why the app should not be compatible with VA4. The only drawback I see is that the app would not make use of the extended capabilities  of the VA4 compared eg. to FR235.
I'm now going to review your PRs.

**Comment by markwmuller** [comment]
Sorry, closed by accident, meant to write -- Thanks! PRs are pretty hacky, but mostly because I don't know exactly what I'm doing. At a minimum, it is working on the VA4s & FR245, but it's probably not implemented as cleanly as you'd like.
