### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by memen45** [andan67/wormnav#7]
Device: vivoactive 4s
App version 1.2.0 from Jan 3rd

Starting the app, loading the track, opening the settings menu, returning to previous pages, it all takes 5+ seconds on my device. Is this normal/expected behaviour? Can it be improved?

**Comment by andan67** [comment]
This is definitely not the expected behaviour. You should expect response times less than 1s.  

Your problem might be caused by a very large track (more than few hundreds of track points). If this is the case, then please reduce the number of track points with the companion app to <400 and try again. 

Another possible cause of your problem might be the refresh period settings. Please check if these are set to 1s.

As a last resort you could try to reinstall the app.

Please let me know if your problem still persists after having tried the above solution proposals.

**Comment by memen45** [comment]
It is indeed quite a large track (1400 waypoints), so that might indeed be related to the slow loading of the track view. However, opening the menu (by long press back button) is also very slow, as well as closing the menu (that's probably the loading map again) and closing the app. Also dwMap app seems to be almost instant in loading the map.

Track and Data views are set to 1s, Auto lap view is set to 10s (default settings).

Is the whole track loaded, computed and drawn each and everytime the screen is refreshed?

**Comment by andan67** [comment]
Please try to reduce the number of track points first. The number of ~400 points is the limit for my FR 235 device given its low memory (64kb!) and performance specs. Though I would expect a much higher limit for your Vivoactive 4s device with 1024kb memory.

As far as I know dwMap reduces the size of the track behind the scenes on track upload. This might explain why dwMap seems to be more responsive.

In the current app version, the track is completely redrawn on each refresh (default 1 s). There are other options which however won't work with my FR235 device and thus are not implemented. This might change in the future, maybe with contributions from other devlopers.

**Comment by andan67** [comment]
I've released a new version in which the track drawing performance should be much faster compared to the previous version.
For my FR235 I've observed a speed-up of factor 2-3.

@memen45 It would be great if you could try out this version and provide feedback on performance improvements.

**Comment by memen45** [comment]
Thanks for suggestions and updating the app! Testing with smaller maps ~400 waypoints is indeed rather quick, so no problems there. 

I have tested the updated version and indeed it is a lot faster than before (~1.5 - 2x faster). Especially opening the menu has improved from 5-10s loading to just responsive on long press of the button, so that is great!

One possible improvement I currently see (apart from reducing loading time of the map of course) is maybe to 'lazy load' the track itself. When opening the app or returning from menu, the watch seems to hang for 5s (for the too large track). This results in confusion (is there a problem? Did the watch get my input). First idea is to load and show the map details (scale) and a 'Loading' text or (even nicer solution) a progress bar while the track is loaded into memory and computed.

Another thing I was wondering: returning from the menu seems to completely reload the track, even though no settings or track has changed. Is this expected? Can the TrackView maybe be optimized to only use waypoints that actually show on the screen 
- having to compute e.g. 10 waypoints within a single pixel just isn't necessary (maybe have a runtime array of 'significant waypoints' for current or even all zoom levels)
- having to compute pixels/waypoints that are outside the boundaries of the screen are also redundant
Maybe some of these optimizations are already applied, I did not check the code in full depth.

Anyways, these are some suggestions. Of course using the android app to limit # of waypoints should also work, although I fear that e.g. large cycling routes will be too inaccurate when zoomed in.

**Comment by andan67** [comment]
Thank you for your feedback.

The current app version performs a redraw of the full track when the view is shown. I've attached a test version for your device where the maximum number of waypoints drawn is limited to 250 when the view is shown. Maybe you could try it out and let me know is this works for you. 

[connectiq.zip](https://github.com/andan67/wormnav/files/6255427/connectiq.zip)

What is the view refresh period when the large track is loaded (can be derived from timer when activity is started)?

Re your optimization ideas: 
Connect IQ supports optimization techniques like partial draw, buffered bitmap and clipping, However, these techniques are not available on my FR235 and thus I haven't yet used them. There are plans to make the code more device/sdk aware to make use of more advanced features on newer devices. 

I think your 'significant waypoints' proposal needs some kind of metrics calculations (like distances between waypoints) to work effectiv ley. Not sure whether  this will result in an additional overhead.

**Comment by andan67** [comment]
The performance has been significantly improved in the current release, so the issue can be closed.  

The partial track redraw idea is not yet released as it is has not been confirmed as being effective for the reported issue.

**Comment by memen45** [comment]
Great to hear and thanks for the update. Sorry for the late response, was not able to test as I fell off the bike. Now I am using the app for a while and it is working great. I usually do optimize to 500 waypoints though (should be better for battery life right?).
Thanks again for the great app!
