### ISSUE TITLE
Spanish translation review

### ISSUE THREAD

**Issue by alsama** [andan67/wormnav#8]
In spanish translation of "dm_labels" in some cases is better to use the word "Lap" for "vueltas" texts as is smaller and fits better in data screens.
I attach and image.
![wormnav_texts_01](https://user-images.githubusercontent.com/28567374/115090204-8be2f000-9f14-11eb-8c6a-8fcb7ebf207b.jpg)

**Comment by andan67** [comment]
In the latest commit https://github.com/andan67/wormnav/commit/23c2813360782f690bfda6271b57a332a3b407eb I've set all data field labels as they appear on my FR 235 for the native apps. Additionally, I've also fixed a stupid bug which resulted in too large font size for vivoactive devices.  

With these changes, the data screen layout looks OK for my FR 235 (all labels in all supported languages fit nicely into the fields). 

However, when running as vivoactive 3 app in the simulator there are still layout issues that are aparently caused by a larger minimum font size compared to the FR 235. So I guess that the vivoactive 3 device uses different data labels than the FR 235.

Unfortunatly, there seems to be no available list of the data field labels as they appear on the screen. The user guides generally show different labels.

I undestand that you own a vivoactive 3 device. Thus it would be great if you could check the data screen layout of the current version and let me know which data field labels are displayed on your device for native apps.

I still aim at using data field labels that are as consistent as possible with the native ones.

**Comment by andan67** [comment]
I've just found out that the labels for non-Englich languages can be easily extrcted from the language files stored on the device in the GARMIN/TXT folder. So it would be great if you could send me these files from your VA3 device.
Thanks

**Comment by alsama** [comment]
Text folder in my va3 (firmware version 7.70):

[TEXT.zip](https://github.com/andan67/wormnav/files/6330132/TEXT.zip)

In general word "vuelta" is used for "Lap" but sometimes "Lap" word is used too.
For example:
01378 Auto Lap
02478 hasta pulsar Lap

In general "lap" term is quite common in spanish language in sports world. And because there is not too much space in data screen I think that is better use "Lap" word instead "vuelta".

**Comment by alsama** [comment]
I have tested commit 23c2813 and I think that "Graphics.FONT_XTINY" is too small to use in a label for a data screen.
I attach an image:

![wormnav_texts_03](https://user-images.githubusercontent.com/28567374/115128974-f01fb580-9fe1-11eb-9f47-499e128b98fa.jpg)


**Left:** commit 23c2813 (using Graphics.FONT_XTINY).
**Center:** Older version translated to spanish using "Lap" word for "vuelta" (using Graphics.FONT_SMALL).
**Right:** Standard 4 fields screen in va3.

I think that standar labels in va3 are using "Graphics.FONT_SMALL" font.

You can see it in "devices.xml" in SDK 3.1.6.
For va3:
 <device family="round-240x240" id="vivoactive3" name="vívoactive® 3" part_number="006-B2700-00">

All languages use font_set="ww"

                <font_set id="ww">
                    <font id="xtiny">FNT_NOTO_SANS_BOLD_16PX</font>
                    <font id="tiny">FNT_NOTO_SANS_BOLD_22PX</font>
                    <font id="small">FNT_NOTO_SANS_BOLD_22PX</font>
                    <font id="medium">FNT_NOTO_SANS_BOLD_25PX</font>
                    <font id="large">FNT_NOTO_SANS_BOLD_25PX</font>
                    <font id="numberMild">FNT_NOTO_SANS_BOLD_29PX</font>
                    <font id="numberMedium">FNT_NOTO_SANS_BOLD_NMBR_48PX</font>
                    <font id="numberHot">FNT_NOTO_SANS_BOLD_NMBR_76PX</font>
                    <font id="numberThaiHot">FNT_NOTO_SANS_BOLD_NMBR_94PX</font>
                    <font id="systemXtiny">FNT_NOTO_SANS_BOLD_16PX</font>
                    <font id="systemTiny">FNT_NOTO_SANS_BOLD_22PX</font>
                    <font id="systemSmall">FNT_NOTO_SANS_BOLD_22PX</font>
                    <font id="systemMedium">FNT_NOTO_SANS_BOLD_25PX</font>
                    <font id="systemLarge">FNT_NOTO_SANS_BOLD_25PX</font>
                    <font id="systemNumberMild">FNT_NOTO_SANS_BOLD_29PX</font>
                    <font id="systemNumberMedium">FNT_NOTO_SANS_BOLD_NMBR_48PX</font>
                    <font id="systemNumberHot">FNT_NOTO_SANS_BOLD_NMBR_76PX</font>
                    <font id="systemNumberThaiHot">FNT_NOTO_SANS_BOLD_NMBR_94PX</font>
                </font_set>

And 4 fields layout use labelfont="small":

                <layout name="4 Fields">
                    <field datafont="numberMedium" datajustify="center" datawidth="165" datax="120" datay="60" height="69" labelfont="small" labeljustify="center" labelx="120" labely="25" left="0" obscurity="5" top="50" width="240" />
                    <field datafont="numberMedium" datajustify="center" datawidth="165" datax="120" datay="60" height="69" labelfont="small" labeljustify="center" labelx="120" labely="25" left="0" obscurity="5" top="120" width="240" />
                </layout>



I attach devices.XML from SDK 3.1.6:
[devices.xml.zip](https://github.com/andan67/wormnav/files/6330192/devices.xml.zip)

**Comment by andan67** [comment]
Thanks for the languages files and the additional  information.
I've noticed that the vivoactive 3 device seems to be special regarding data screen layout and available fonts, which makes a 'generic' layout calculation a bit more difficult.

In the latest commit I've changed all data field lables according to the language files (using their shortest version).
I've also changed the data screen layout and used your idea of setting on offset.
For me, the layout now looks 'good enough' for all supported languages with standard data field names.

It would be great if you could let me know your thoughts on the changes.

**Comment by alsama** [comment]
I think that layout is better now because all fields are near center and so labels have more free space than near the top. Also the new label texts looks good. Using "vue" or "vuel." instead "lap" is good too.
And using that labels I think that is possible use to use "Graphics.FONT_SMALL" font.
And that have several adventages.
* It was the font that was used in older version so users will see a similar layout.
* "Graphics.FONT_XTINY" is very little and difficult to read especially when you practise a sport.
* I think "Graphics.FONT_SMALL" font is the font used in standar va3 activity screens labels.

I put some photos of both options in my va3:
![wormnav_texts_05](https://user-images.githubusercontent.com/28567374/115208342-bbece780-a0fc-11eb-837b-48b243b49f6e.jpg)
![wormnav_texts_06](https://user-images.githubusercontent.com/28567374/115208377-c6a77c80-a0fc-11eb-8fce-c556e990e892.jpg)
